### ISSUE TITLE
如何将数据按图片处理

### ISSUE THREAD

**Issue by LiangHaoran** [abanger/DCIC2019-Concrete-Pump-Vehicles#1]
您好，请问能稍微讲讲将数据按图片处理的思路吗？每个文件中的数据数量都不一样，如果按照一定窗口长度去截断，可能会出现除不尽的余数，我看您的代码里是补全了，那具体用什么东西补全数据呢？ 谢谢了

**Comment by abanger** [comment]
因为数据不是生产数据，这方法还没确认。简单把每个数据看成点，行列形成一张单色图。补全是用平均值，实际你可试试其他方法如中值。
