### ISSUE TITLE
data_train2cnn100.py.py

### ISSUE THREAD

**Issue by huminwudi** [abanger/DCIC2019-Concrete-Pump-Vehicles#2]
您好！，这个文件夹中doclen=10460160//20，这两个数字是什么意思呢？新人在学习

**Comment by abanger** [comment]
思路，参考一下，实际数据可能效果会好点。
'''
doclen=0
for f in fm: 
    #ff= os.listdir(path+'\\'+f+'\\') 
    td=pd.read_csv(path+'/data_train/'+f )
    tlen=td.shape[0]
    if tlen%20!=0:
        tlen=tlen+20-tlen%20
    doclen+=tlen
print(doclen)
'''
由上面一段产生
每个文件长度不能被20整除还得再补到长度可被20整除，doclen所有文件长度和，doclen/20为最终图片数量。

**Comment by huminwudi** [comment]
谢谢您的答复，可以在问一下，为什么会选择20作为这个度量，不可以选择其他  比如10  30这种吗？

**Comment by abanger** [comment]
> 谢谢您的答复，可以在问一下，为什么会选择20作为这个度量，不可以选择其他 比如10 30这种吗？

可以的，要经测试才知道效果如何，太小可能找不到差别。
